"""
File where constants are maintained.
Used to avoid typos

"""


# region filenames

DLH_BOOKS = "DLH_BOOKS.pickle"
ROUGH_DLH_PROPER_NOUNS = "rough_dlh_proper_nouns.pickle"
LATIN_TOKENS = "latin_tokens.pickle"
DLH_PROPER_NOUNS = "dlh_proper_nouns.txt"
CLOSE_PROPER_NOUNS = "close_proper_nouns.pickle"
DISTANCE_PROPER_NOUNS_DLH = "distance_proper_nouns_dlh.ndarray"
CLUSTERISED_PROPER_NOUNS_DLH = "LEMMATIZED_PROPER_NOUNS_DLH.pickle"
LEMMATISED_DLH_PROPER_NOUNS = "LEMMATISED_DLH_PROPER_NOUNS.txt"
LEMMATISED_DLH_CLEAN_PROPER_NOUNS = "LEMMATISED_DLH_CLEAN_PROPER_NOUNS.txt"  # annotated version
LEMMATISED_DLH_CLEAN_PERSON_NAMES = "LEMMATIZED_DLH_CLEAN_PERSON_NAMES.txt"  # annotated version
LEMMATISED_DLH_CLEAN_PLACES = "LEMMATIZED_DLH_CLEAN_PLACES.txt"  # annotated version
DLH_GRAPHS_DIRECTORY = "dlh_graphs"

VOLSUNGA_PROPER_NOUNS = "VOLSUNGA_PROPER_NOUNS.pickle"
CLUSTERED_VOLSUNGA_PROPER_NOUNS = "VOLSUNGA_CLUSTERED_PROPER_NOUNS.pickle"
RESULT_VOLSUNGA_PROPER_NOUNS = "VOLSUNGA_RESULT_PROPER_NOUNS.txt"
VOLSUNGA_CLEAN_NAMES_PROPER_NOUNS = "VOLSUNGA_CLEAN_NAMES_PROPER_NOUNS.txt"
VOLSUNGA_CLEAN_OBJECTS_PROPER_NOUNS = "VOLSUNGA_CLEAN_OBJECTS_PROPER_NOUNS.txt"
VOLSUNGA_CLEAN_PLACES_PROPER_NOUNS = "VOLSUNGA_CLEAN_PLACES_PROPER_NOUNS.txt"
VOLSUNGA_CLEAN_GROUP_PROPER_NOUNS = "VOLSUNGA_CLEAN_GROUP_PROPER_NOUNS.txt"
VOLSUNGA_GRAPHS_DIRECTORY = "vol_graphs"

NIB_C_PROPER_NOUNS = "NIB_C_PROPER_NOUNS.pickle"
CLUSTERED_NIB_C_PROPER_NOUNS = "NIB_C_CLUSTERED_PROPER_NOUNS.pickle"
NIB_C_CLEAN_PROPER_NOUNS = "NIB_C_CLEAN_PROPER_NOUNS.txt"
NIB_GRAPHS_DIRECTORY = "nib_graphs"

DISTANCE_PROPER_NOUNS = "DISTANCE_PROPER_NOUNS"
# endregion

PUNCTUATIONS = "\"'?!.,;:"

DLH_DIRECTORY = "dlh"
DLH_GRAPH_BY_CHAPTERS = "dlh_graph_by_chapters.pickle"
DLH_GRAPH = "dlh_graph.pickle"

VOL_DIRECTORY = "volsunga"
VOL_GRAPH_BY_CHAPTER = "vol_graph_by_chapter.pickle"
VOL_GRAPH = "vol_graph.pickle"

NIB_DIRECTORY = "nibelungenlied"
NIB_GRAPH_BY_CHAPTER = "nib_graph_by_chapter.pickle"
NIB_GRAPH = "nib_graph.pickle"
